### ISSUE TITLE
VAB bogs down to 3FPS when no engine attached

### ISSUE THREAD

**Issue by Atario** [HebaruSan/SmartTank#2] opened 2017-10-09 09:14 UTC
As soon as I attach one, it goes back to 60FPS.  Disabling auto-sizing on the PP tank also solves it.

Could be some conflict with Infernal Robotics or BetterCrewAssignment or both, since the log immediately begins rapidly filling stuff from them during the slowdown.  I've only shown three repetitions of this block of logs here for brevity, but it seems to spam these at a rate of around 20 blocks per second (!) for the duration of the slowdown.

Snippet follows.

```
IR: [ServoController] OnEditorShipModified finished successfully
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

10/9/2017 1:59:49 AM,IRSequencer-IRWrapper,Attempting to Grab IR Types...
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

10/9/2017 1:59:49 AM,IRSequencer-IRWrapper,IR Version:2.0.9.0
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

10/9/2017 1:59:49 AM,IRSequencer-IRWrapper,Got Assembly Types, grabbing Instance
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

10/9/2017 1:59:49 AM,IRSequencer-IRWrapper,Got Instance, Creating Wrapper Objects
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

10/9/2017 1:59:49 AM,IRSequencer-IRWrapper,Getting APIReady Object
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

10/9/2017 1:59:49 AM,IRSequencer-IRWrapper,Success: True
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

[BetterCrewAssignment] Ship modified, 2 parts.
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

[BetterCrewAssignment] Crew assignment complete. Assigned 0 kerbals, left 0 slots empty.
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

IR: [ServoController] OnEditorShipModified finished successfully
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

10/9/2017 1:59:49 AM,IRSequencer-IRWrapper,Attempting to Grab IR Types...
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

10/9/2017 1:59:49 AM,IRSequencer-IRWrapper,IR Version:2.0.9.0
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

10/9/2017 1:59:49 AM,IRSequencer-IRWrapper,Got Assembly Types, grabbing Instance
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

10/9/2017 1:59:49 AM,IRSequencer-IRWrapper,Got Instance, Creating Wrapper Objects
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

10/9/2017 1:59:49 AM,IRSequencer-IRWrapper,Getting APIReady Object
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

10/9/2017 1:59:49 AM,IRSequencer-IRWrapper,Success: True
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

[BetterCrewAssignment] Ship modified, 2 parts.
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

[BetterCrewAssignment] Crew assignment complete. Assigned 0 kerbals, left 0 slots empty.
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

IR: [ServoController] OnEditorShipModified finished successfully
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

10/9/2017 1:59:49 AM,IRSequencer-IRWrapper,Attempting to Grab IR Types...
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

10/9/2017 1:59:49 AM,IRSequencer-IRWrapper,IR Version:2.0.9.0
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

10/9/2017 1:59:49 AM,IRSequencer-IRWrapper,Got Assembly Types, grabbing Instance
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

10/9/2017 1:59:49 AM,IRSequencer-IRWrapper,Got Instance, Creating Wrapper Objects
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

10/9/2017 1:59:49 AM,IRSequencer-IRWrapper,Getting APIReady Object
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

10/9/2017 1:59:49 AM,IRSequencer-IRWrapper,Success: True
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

[BetterCrewAssignment] Ship modified, 2 parts.
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

[BetterCrewAssignment] Crew assignment complete. Assigned 0 kerbals, left 0 slots empty.
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

```

**Comment by HebaruSan** [comment] 2017-10-09 19:58
> Disabling auto-sizing on the PP tank also solves it.

Exactly which toggle is that? A screenshot of the part's right click menu when the problem is happening could be very helpful.

**Comment by Atario** [comment] 2017-10-23 10:47
It was "Auto fit to attached parts", but sadly I can't replicate the problem now.  `:/`

**Comment by HebaruSan** [comment] 2017-10-23 17:05
In that case, I'm going to close this issue as I won't be investigating it. If you are able to replicate it later, please add another comment and I'll re-open it. Thanks for reporting.

**Closed as completed by HebaruSan** 2017-10-23 17:05 UTC
